#!/usr/bin/env python3

import argparse
from yaml import load, Loader

from opustools_pkg import OpusFilter

parser = argparse.ArgumentParser(prog='opus_filter',
    description='Filter OPUS bitexts')

parser.add_argument('-f', help='yaml configuration file', required=True)

args = parser.parse_args()

configuration = load(open(args.f), Loader=Loader)

of = OpusFilter(configuration)
of.execute_steps()
