from .test_block_parser import TestBlockParser
from .test_sentence_parser import TestSentenceParser
from .test_alignment_parser import TestAlignmentParser
from .test_2_new_opus_read import TestOpusRead
